var loaded_sys_fonts_ = [
  '@Arial Unicode MS',
  '@DFGothic-EB',
  '@DFMincho-SU',
  '@DFMincho-UB',
  '@DFPOP1-W9',
  '@MS Gothic',
  '@MS Mincho',
  '@MS PGothic',
  '@MS UI Gothic',
  '@Malgun Gothic',
  '@Malgun Gothic Semilight',
  '@Microsoft JhengHei',
  '@Microsoft JhengHei Light',
  '@Microsoft JhengHei UI',
  '@Microsoft JhengHei UI Light',
  '@Microsoft YaHei',
  '@Microsoft YaHei Light',
  '@Microsoft YaHei UI',
  '@Microsoft YaHei UI Light',
  '@MingLiU-ExtB',
  '@MingLiU_HKSCS-ExtB',
  '@NSimSun',
  '@PMingLiU-ExtB',
  '@SimSun',
  '@SimSun-ExtB',
  '@Yu Gothic',
  '@Yu Gothic Light',
  '@Yu Gothic Medium',
  '@Yu Gothic UI',
  '@Yu Gothic UI Light',
  '@Yu Gothic UI Semibold',
  '@Yu Gothic UI Semilight',
  '@ＤＦ中太楷書体',
  '@ＤＦ明朝体W5',
  'Agency FB',
  'Alegreya Sans SC',
  'Alegreya Sans SC Black',
  'Alegreya Sans SC ExtraBold',
  'Alegreya Sans SC Light',
  'Alegreya Sans SC Medium',
  'Alegreya Sans SC Thin',
  'Algerian',
  'Arabic Transparent',
  'Arial',
  'Arial Baltic',
  'Arial Black',
  'Arial CE',
  'Arial CYR',
  'Arial Cyr',
  'Arial Greek',
  'Arial Narrow',
  'Arial Rounded MT Bold',
  'Arial TUR',
  'Arial Unicode MS',
  'Bahnschrift',
  'Bahnschrift Condensed',
  'Bahnschrift Light',
  'Bahnschrift Light Condensed',
  'Bahnschrift Light SemiCondensed',
  'Bahnschrift SemiBold',
  'Bahnschrift SemiBold Condensed',
  'Bahnschrift SemiBold SemiConden',
  'Bahnschrift SemiCondensed',
  'Bahnschrift SemiLight',
  'Bahnschrift SemiLight Condensed',
  'Bahnschrift SemiLight SemiConde',
  'Baskerville Old Face',
  'Bauhaus 93',
  'Bebas Neue Bold',
  'Bebas Neue Book',
  'Bebas Neue Light',
  'Bebas Neue Regular',
  'Bebas Neue Thin',
  'Bell MT',
  'Berlin Sans FB',
  'Berlin Sans FB Demi',
  'Bernard MT Condensed',
  'Bison',
  'Bison Bold',
  'Bison Bold Itallic',
  'Bison Demi Bold',
  'Bison Demi Bold Itallic',
  'Bison Italic',
  'Bison Light',
  'Bison Light Italic',
  'Bison Thick Outline',
  'Bison Thick Outline Itallic',
  'Bison Thin Outline',
  'Bison Thin Outline Itallic',
  'Blackadder ITC',
  'Bodoni Bd BT',
  'Bodoni Bk BT',
  'Bodoni MT',
  'Bodoni MT Black',
  'Bodoni MT Condensed',
  'Bodoni MT Poster Compressed',
  'Book Antiqua',
  'Bookman Old Style',
  'Bookshelf Symbol 7',
  'Bradley Hand ITC',
  'Britannic Bold',
  'Broadway',
  'Brush Script MT',
  'Calibri',
  'Calibri Light',
  'Californian FB',
  'Calisto MT',
  'Cambria',
  'Cambria Math',
  'Candara',
  'Candara Light',
  'Castellar',
  'CentSchbkCyrill BT',
  'Centaur',
  'Century',
  'Century Gothic',
  'Century Schoolbook',
  'Century725 Cn BT',
  'Century751 BT',
  'Century751 No2 BT',
  'Century751 SeBd BT',
  'Chiller',
  'Clarendon BT',
  'Clarendon Blk BT',
  'Clarendon Lt BT',
  'Colonna MT',
  'Comic Sans MS',
  'Consolas',
  'Constantia',
  'Cooper Black',
  'Copperplate Gothic Bold',
  'Copperplate Gothic Light',
  'Corbel',
  'Corbel Light',
  'Courier',
  'Courier New',
  'Courier New Baltic',
  'Courier New CE',
  'Courier New CYR',
  'Courier New Cyr',
  'Courier New Greek',
  'Courier New TUR',
  'Curlz MT',
  'DFGothic-EB',
  'DFMincho-SU',
  'DFMincho-UB',
  'DFPOP1-W9',
  'DINCondensedCTT',
  'DINCyr-Black',
  'DINCyr-BlackAlternate',
  'DINCyr-Bold',
  'DINCyr-BoldAlternate',
  'DINCyr-Light',
  'DINCyr-LightAlternate',
  'DINCyr-Medium',
  'DINCyr-MediumAlternate',
  'DINCyr-Regular',
  'DINCyr-RegularAlternate',
  'DeVinne Txt BT',
  'Designball-Arrow-01',
  'Designball-Arrow-02',
  'Designball-Art-Design-01',
  'Designball-Art-Design-02',
  'Designball-Buildings-01',
  'Designball-Charts-01',
  'Designball-Communication-01',
  'Designball-Documents-01',
  'Designball-Documents-02',
  'Designball-Electronic-Device-01',
  'Designball-Electronic-Device-02',
  'Designball-Finance-01',
  'Designball-Location-01',
  'Designball-Social-01',
  'Designball-Users-01',
  'Designball-Users-02',
  'Designball-edu-01',
  'Designball-edu-02',
  'Designball-emotions-01',
  'Ebrima',
  'Edwardian Script ITC',
  'Elephant',
  'Embassy BT',
  'Engravers MT',
  'EngraversGothic BT',
  'Eras Bold ITC',
  'Eras Demi ITC',
  'Eras Light ITC',
  'Eras Medium ITC',
  'Exotc350 Bd BT',
  'Exotc350 DmBd BT',
  'Felix Titling',
  'Fixedsys',
  'Footlight MT Light',
  'Formular',
  'Forte',
  'Franklin Gothic Book',
  'Franklin Gothic Demi',
  'Franklin Gothic Demi Cond',
  'Franklin Gothic Heavy',
  'Franklin Gothic Medium',
  'Franklin Gothic Medium Cond',
  'Freehand521 BT',
  'Freestyle Script',
  'French Script MT',
  'Futura Bk BT',
  'Futura Md BT',
  'Gabriola',
  'Gadugi',
  'Garamond',
  'GeoSlab703 Md BT',
  'GeoSlab703 MdCn BT',
  'Geometr212 BkCn BT',
  'Geometr415 Blk BT',
  'Geometr706 BlkCn BT',
  'Georgia',
  'Gigi',
  'Gill Sans MT',
  'Gill Sans MT Condensed',
  'Gill Sans MT Ext Condensed Bold',
  'Gill Sans Ultra Bold',
  'Gill Sans Ultra Bold Condensed',
  'Gilroy ExtraBold',
  'Gilroy Light',
  'Gloucester MT Extra Condensed',
  'Gotham Pro',
  'Gotham Pro Black',
  'Gotham Pro Light',
  'Gotham Pro Medium',
  'Goudy Old Style',
  'Goudy Stout',
  'Haettenschweiler',
  'Harlow Solid Italic',
  'Harrington',
  'Heading Pro',
  'Heading Pro Book',
  'Heading Pro ExtBd',
  'Heading Pro ExtLt',
  'Heading Pro Heavy',
  'Heading Pro Light',
  'Heading Pro Thin',
  'Helios',
  'Helvetica',
  'Helvetica Bold',
  'Helvetica Bold Oblique',
  'Helvetica Light',
  'Helvetica Light Oblique',
  'Helvetica Oblique',
  'High Tower Text',
  'HoloLens MDL2 Assets',
  'Humanst521 BT',
  'Humanst521 Lt BT',
  'Humnst777 BT',
  'Humnst777 Blk BT',
  'Humnst777 BlkCn BT',
  'Humnst777 Cn BT',
  'Humnst777 Lt BT',
  'Impact',
  'Imprint MT Shadow',
  'Informal Roman',
  'Ink Free',
  'Javanese Text',
  'Jokerman',
  'Juice ITC',
  'Kaufmann BT',
  'Kristen ITC',
  'Kunstler Script',
  'Leelawadee UI',
  'Leelawadee UI Semilight',
  'Lucida Bright',
  'Lucida Calligraphy',
  'Lucida Console',
  'Lucida Fax',
  'Lucida Handwriting',
  'Lucida Sans',
  'Lucida Sans Typewriter',
  'Lucida Sans Unicode',
  'MS Gothic',
  'MS Mincho',
  'MS Outlook',
  'MS PGothic',
  'MS Reference Sans Serif',
  'MS Reference Specialty',
  'MS Sans Serif',
  'MS Serif',
  'MS UI Gothic',
  'MT Extra',
  'MV Boli',
  'Magneto',
  'Maiandra GD',
  'Malgun Gothic',
  'Malgun Gothic Semilight',
  'Marlett',
  'Matura MT Script Capitals',
  'Microsoft Himalaya',
  'Microsoft JhengHei',
  'Microsoft JhengHei Light',
  'Microsoft JhengHei UI',
  'Microsoft JhengHei UI Light',
  'Microsoft New Tai Lue',
  'Microsoft PhagsPa',
  'Microsoft Sans Serif',
  'Microsoft Tai Le',
  'Microsoft YaHei',
  'Microsoft YaHei Light',
  'Microsoft YaHei UI',
  'Microsoft YaHei UI Light',
  'Microsoft Yi Baiti',
  'Mike Sans Free',
  'MingLiU-ExtB',
  'MingLiU_HKSCS-ExtB',
  'Mistral',
  'Modern',
  'Modern No. 20',
  'Mongolian Baiti',
  'Monotype Corsiva',
  'Montserrat',
  'Montserrat Black',
  'Montserrat ExtraBold',
  'Montserrat ExtraLight',
  'Montserrat Light',
  'Montserrat Medium',
  'Montserrat SemiBold',
  'Montserrat Thin',
  'Myanmar Text',
  'NSimSun',
  'News701 BT',
  'News706 BT',
  'NewsGoth BT',
  'NewsGoth Lt BT',
  'Niagara Engraved',
  'Niagara Solid',
  'Nirmala UI',
  'Nirmala UI Semilight',
  'Norwester',
  'OCR A Extended',
  'OCR-A BT',
  'OCR-B 10 BT',
  'Old English Text MT',
  'Onyx',
  'PF Bague Sans Pro',
  'PMingLiU-ExtB',
  'Palace Script MT',
  'Palatino Linotype',
  'Papyrus',
  'Parchment',
  'Peace Sans',
  'Perpetua',
  'Perpetua Titling MT',
  'Playbill',
  'Ponter S',
  'Poor Richard',
  'Pristina',
  'Rage Italic',
  'Ravie',
  'Roboto',
  'Roboto Bk',
  'Roboto Cn',
  'Roboto Lt',
  'Roboto Slab',
  'Roboto Th',
  'Rockwell',
  'Rockwell Condensed',
  'Rockwell Extra Bold',
  'Roman',
  'Schadow BT',
  'Script',
  'Script MT Bold',
  'Segoe MDL2 Assets',
  'Segoe Print',
  'Segoe Script',
  'Segoe UI',
  'Segoe UI Black',
  'Segoe UI Emoji',
  'Segoe UI Historic',
  'Segoe UI Light',
  'Segoe UI Semibold',
  'Segoe UI Semilight',
  'Segoe UI Symbol',
  'Showcard Gothic',
  'SimSun',
  'SimSun-ExtB',
  'Sitka Banner',
  'Sitka Display',
  'Sitka Heading',
  'Sitka Small',
  'Sitka Subheading',
  'Sitka Text',
  'Small Fonts',
  'Snap ITC',
  'Square721 BT',
  'Square721 Cn BT',
  'Stencil',
  'Swis721 BT',
  'Swis721 Blk BT',
  'Swis721 BlkCn BT',
  'Swis721 Cn BT',
  'Swis721 Hv BT',
  'Swis721 Lt BT',
  'Swis721 LtEx BT',
  'Swis721 WGL4 BT',
  'Sylfaen',
  'Symbol',
  'System',
  'Tahoma',
  'Tempus Sans ITC',
  'Terminal',
  'Times New Roman',
  'Times New Roman Baltic',
  'Times New Roman CE',
  'Times New Roman CYR',
  'Times New Roman Cyr',
  'Times New Roman Greek',
  'Times New Roman TUR',
  'Trebuchet MS',
  'Tw Cen MT',
  'Tw Cen MT Condensed',
  'Tw Cen MT Condensed Extra Bold',
  'TypoUpright BT',
  'Unvoll',
  'Verdana',
  'Viner Hand ITC',
  'Vivaldi',
  'Vladimir Script',
  'Webdings',
  'Wide Latin',
  'Wingdings',
  'Wingdings 2',
  'Wingdings 3',
  'Yu Gothic',
  'Yu Gothic Light',
  'Yu Gothic Medium',
  'Yu Gothic UI',
  'Yu Gothic UI Light',
  'Yu Gothic UI Semibold',
  'Yu Gothic UI Semilight',
  'ＤＦ中太楷書体',
  'ＤＦ明朝体W5',
]
