export const actions = {
  CHANGE_ENTITY: 'change-entity',
  ADD_ENTITY: 'add-entity',
  DELETE_ENTITY: 'delete-entity',
  SET_ACTIVE_SETTINGS_TAB: 'set-active-settings-tab',
  SET_SELECTED: 'set-selected',
  SET_SYSTEM_FONTS: 'set-system-fonts',
  SET_PRINTING_MODE: 'set-printing-mode',
  CHANGE_SIDE_NEED_PRINT: 'change-side-need-print',
  SET_IMAGE_FILE: 'set-image-file',
  SET_DATA_SOURCE: 'set-data-source',
  EDIT_DATA_SOURCE: 'edit-data-source',
  DELETE_DATA_SOURCE: 'delete-data-source',
  SET_DATA: 'set-data',
  SET_STATE: 'set-state',
}
