import { dataSelectorModeInfo } from '../../utils'

export const defaultObjects = {
  txt: {
    type: 'txt',
    selected: false,
    top: '45',
    left: '10',
    width: '45',
    height: '7',
    align: 'center',
    color: 'black',
    fontFamily: 'Arial',
    fontSize: '12',
    fontWeight: 'normal',
    fontStyle: 'normal',
    textDecoration: 'none',
    textBorderWidth: 1,
    textBorderColor: '#0074A7',
    rotate: 0,
    data_source_id: '',
    data: [],
  },
  qrcode: {
    type: 'qrcode',
    selected: false,
    level: 'M',
    margin: 7,
    scale: 1,
    pixelWwidth: 4,
    width: 12,
    top: '36',
    left: '67.5',
    darkColor: '#000',
    lightColor: '#FFF',
    rotate: 0,
    data_source_id: '',
    data: [],
  },
  barcode: {
    type: 'barcode',
    format: 'code128',
    selected: false,
    top: '36.6',
    left: '40.5',
    width: '43.6',
    height: '14.2',
    fontSize: '35',
    textPosition: 'bottom',
    displayValue: true,
    flat: false,
    barWidth: 2.5,
    rotate: 0,
    data_source_id: '',
    data: [],
  },
  dataSource: {
    editing_source_name: '',
    data_selector_mode: dataSelectorModeInfo[0][0],
    selected_indexes: [],
    diapason: { from: 0, to: 0 },
    sources: {},
  },
  common: {
    frontImage: { content: null },
    backImage: { content: null },
    imagesDataURL: {
      front: null,
      back: null,
    },
    active_settings_tab: 'front',
    active_settings_side: 'front',
    systemFonts: [],
    printingMode: 'grid',
    needPrint: {
      front: true,
      back: true,
    },
  },
}
